### ISSUE TITLE
Return failed reason instead of None when calling polyaxon_client.experiment_group.get_experiment_group()

### ISSUE THREAD

**Issue by bestksw** [polyaxon/polyaxon-client#35]
Hi, polyaxon team.
When the server is busy, it returns None, also when given group id doesn't exist, it also return None. The example code looks like below.
```
>>> polyaxon_client.experiment_group.get_experiment_group('username', 'projectname', 88)
None
```
When that function return None, I cannot assure the server is busy (429 Too Many Requests) or given experiment group doesn't exist.

I request you for the server to return reason like this {"status_code": 404, "detail": "Not found."} instead of None.

**Comment by mouradmourafiq** [comment]
You can do the following: `polyaxon_client.set_reraise(True)` and handle the exceptions yourself, the exception will handling should be:

```
try:
    polyaxon_client.experiment_group.get_experiment_group('username', 'projectname', 88)
except PolyaxonClientException as e:
    print(e.status_code)
```

**Comment by bestksw** [comment]
It works. Thank you!
