### ISSUE TITLE
can't see in the docs how to set the ip address for tracking api

### ISSUE THREAD

**Issue by dasturge** [polyaxon/polyaxon-client#39]
Everything else is working in terms of submitting jobs, but my tracking api is trying to reach `http://polyaxon-polyaxon-api:80/`, which is not where my instance of polyaxon is hosted.

e.g.

```
from polyaxon_client.tracking import Experiment`
experiment = Experiment(project="myproject")`
metric = 5'
experiment.log_params(metric=metric)
```

gives: `ERROR:polyaxon.client:Request to http://polyaxon-polyaxon-api:80/api/v1/myproject/experiments/ failed with status code 404.`

the job still runs as normal but it looks like none of the logging is working.

**Comment by mouradmourafiq** [comment]
If you are using the client from outside of Polyaxon you can use this guide: https://docs.polyaxon.com/references/polyaxon-tracking-api/other-environments/

If you are running a job scheduled by Polyaxon it will get authenticated automatically, see: https://docs.polyaxon.com/references/polyaxon-tracking-api/in-cluster-experiments/
